---
title: "Regresiones Lineales - Ejemplo Calificadoras"
output: html_notebook
---

#### Paquetes
```{r}
#install.packages("R2OpenBUGS")
#install.packages("R2jags")
```

#### Librerias
```{r}
library(R2OpenBUGS)
library(R2jags)
```

####-Working directory-
```{r}
wdir<-"/Users/guillemontanari/ITAM/github/GLM2016/RegresionLinealJAGS"
setwd(wdir)
```

### Funciones Útiles
```{r}
prob<-function(x){
  out<-min(length(x[x>0])/length(x),length(x[x<0])/length(x))
  out
}
```

### Leemos los datos de un archivo txt
```{r}
#--- Ejemplo 3 ---
#-Reading data-
calif<-read.table("http://allman.rhon.itam.mx/~lnieto/index_archivos/calificaciones.txt",header=TRUE)
n<-nrow(calif)
plot(calif$MO, calif$SP)
```
### Defining data - siempre como lista para JAGS
```{r}
data<-list("n"=n,"y"=calif$SP,"x"=calif$MO)
```
### Defining inits
```{r}
inits<-function(){list(beta=rep(0,2),tau=1,yf=rep(0,n))}
```
### Defining parametros a monitorear
```{r}
parameters<-c("beta","tau","yf")
```
### Ejecutamos la simulacion
```{r}
ej3.sim<-jags(data,inits,parameters,model.file="Ej3_a.txt",
              n.iter=1000000,n.chains=1,n.burnin=10000,n.thin=1)
```
### Monitoreamos la cadena
#### Traza
```{r}
traceplot(ej3.sim)
```
#### Cadena
```{r}
out<-ej3.sim$BUGSoutput$sims.list
# Guardo los valores de Beta2 en Z: Beta2 son los coeficientes asociados a las xi's
z<-out$beta[,2]
# Defino 4 zonas de ploteo
par(mfrow=c(2,2))

plot(z,type="l")
plot(cumsum(z)/(1:length(z)),type="l")
hist(z,freq=FALSE)
acf(z)
```
### Correlacion
```{r}
z<-out$beta
# Defino 1 zona de ploteo
par(mfrom=c(1,1))
plot(z)
```
### Resumen de estimadores
```{r}
out.sum<-ej3.sim$BUGSoutput$summary
print(out.sum)
head(out.sum)
```
### Probabilidades
```{r}
z<-out$beta[,1]
prob(z)
hist(z,freq=FALSE)
abline(v=0,col=2)
```
### DIC
```{r}
out.dic<-ej3.sim$BUGSoutput$DIC
print(out.dic)
```
### Predicciones
```{r}
out.yf<-out.sum[grep("yf",rownames(out.sum)),]
or<-order(calif$MO)
ymin<-min(calif$SP,out.yf[,c(1,3,7)])
ymax<-max(calif$SP,out.yf[,c(1,3,7)])
par(mfrow=c(1,1))
plot(calif$MO,calif$SP,ylim=c(ymin,ymax))
lines(calif$MO[or],out.yf[or,1],lwd=2,col=2)
lines(calif$MO[or],out.yf[or,3],lty=2,col=2)
lines(calif$MO[or],out.yf[or,7],lty=2,col=2)

out.yf<-out.sum[grep("yf",rownames(out.sum)),]
lines(calif$MO[or],out.yf[or,1],lwd=2,col=4)
lines(calif$MO[or],out.yf[or,3],lty=2,col=4)
lines(calif$MO[or],out.yf[or,7],lty=2,col=4)
```




















